// ICAO callsign prefix -> airline name.
// Majors, US regionals/cargo, PNW operators, and common medevac/utility callsigns.
module.exports = {
  AAL: 'American Airlines',
  ACA: 'Air Canada',
  AFR: 'Air France',
  AIC: 'Air India',
  AMX: 'Aeroméxico',
  ANA: 'All Nippon Airways',
  ASA: 'Alaska Airlines',
  ASH: 'Mesa Airlines',
  AWI: 'Air Wisconsin',
  BAW: 'British Airways',
  BOE: 'Boeing',
  CAL: 'China Airlines',
  CES: 'China Eastern',
  CFS: 'Empire Airlines (FedEx Feeder)',
  CKS: 'Kalitta Air',
  CMP: 'Copa Airlines',
  CPA: 'Cathay Pacific',
  CPZ: 'Compass Airlines',
  DAL: 'Delta Air Lines',
  DLH: 'Lufthansa',
  EDV: 'Endeavor Air',
  EIN: 'Aer Lingus',
  EJA: 'NetJets',
  EJM: 'Executive Jet Management',
  ELY: 'El Al',
  ENY: 'Envoy Air',
  ETD: 'Etihad Airways',
  ETH: 'Ethiopian Airlines',
  EVA: 'EVA Air',
  FDX: 'FedEx Express',
  FFT: 'Frontier Airlines',
  FIN: 'Finnair',
  GEC: 'Lufthansa Cargo',
  GTI: 'Atlas Air',
  HAL: 'Hawaiian Airlines',
  IBE: 'Iberia',
  ICE: 'Icelandair',
  JAL: 'Japan Airlines',
  JBU: 'JetBlue',
  JZA: 'Air Canada Express (Jazz)',
  KAL: 'Korean Air',
  KAP: 'Cape Air',
  KLM: 'KLM',
  LXJ: 'Flexjet',
  MXY: 'Breeze Airways',
  NCA: 'Nippon Cargo Airlines',
  NKS: 'Spirit Airlines',
  OAE: 'Omni Air International',
  PAC: 'Polar Air Cargo',
  PCM: 'West Air (FedEx Feeder)',
  PDT: 'Piedmont Airlines',
  QFA: 'Qantas',
  QTR: 'Qatar Airways',
  QXE: 'Horizon Air',
  RPA: 'Republic Airways',
  RYR: 'Ryanair',
  SAS: 'Scandinavian Airlines',
  SCX: 'Sun Country Airlines',
  SIA: 'Singapore Airlines',
  SKW: 'SkyWest Airlines',
  SWA: 'Southwest Airlines',
  TSC: 'Air Transat',
  UAE: 'Emirates',
  UAL: 'United Airlines',
  UPS: 'UPS Airlines',
  VIR: 'Virgin Atlantic',
  VOI: 'Volaris',
  VXP: 'Avelo Airlines',
  WJA: 'WestJet',
  XOJ: 'XOJET',
};
